/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sZQMbqXz9utLNaTnNb3uss
// Component: TplLKZCFlHXj

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Input } from "@/fragment/components/input"; // plasmic-import: UGm7T3K14yEW/codeComponent
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sZQMbqXz9utLNaTnNb3uss/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sZQMbqXz9utLNaTnNb3uss/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: sZQMbqXz9utLNaTnNb3uss/projectcss
import sty from "./PlasmicLogIn2.module.css"; // plasmic-import: TplLKZCFlHXj/css

import Icon37Icon from "./icons/PlasmicIcon__Icon37"; // plasmic-import: T5qnRYhm3_iD/icon

createPlasmicElementProxy;

export type PlasmicLogIn2__VariantMembers = {};
export type PlasmicLogIn2__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogIn2__VariantsArgs;
export const PlasmicLogIn2__VariantProps = new Array<VariantPropType>();

export type PlasmicLogIn2__ArgsType = {
  number?: string;
  onNumberChange?: (val: string) => void;
  disabled?: boolean;
};
type ArgPropType = keyof PlasmicLogIn2__ArgsType;
export const PlasmicLogIn2__ArgProps = new Array<ArgPropType>(
  "number",
  "onNumberChange",
  "disabled"
);

export type PlasmicLogIn2__OverridesType = {
  root?: Flex__<"div">;
  fragmentInput?: Flex__<typeof Input>;
  freeBox?: Flex__<"div">;
  select2?: Flex__<typeof AntdSelect>;
  svg?: Flex__<"svg">;
};

export interface DefaultLogIn2Props {
  number?: string;
  onNumberChange?: (val: string) => void;
  disabled?: boolean;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogIn2__RenderFunc(props: {
  variants: PlasmicLogIn2__VariantsArgs;
  args: PlasmicLogIn2__ArgsType;
  overrides: PlasmicLogIn2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "fragmentInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "number",
        type: "writable",
        variableType: "text",

        valueProp: "number",
        onChangeProp: "onNumberChange"
      },
      {
        path: "error",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "time",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return 60;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return 60;
              }
              throw e;
            }
          })()
      },
      {
        path: "loadedbtn",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "code",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      },
      {
        path: "saraf",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          { label: "sjsjd1n", value: 101 },
          { label: "sjs2jdn", value: 102 },
          { label: "sjsj3dn", value: 103 },
          { label: "sjs4jdn", value: 104 }
        ]
      },
      {
        path: "selectsaraf",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      },
      {
        path: "pass",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "pass1",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "password"
      },
      {
        path: "contry",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          {
            value: "+98",
            label: "\ud83c\uddee\ud83c\uddf7 +98",
            description: "Iran",
            phoneFormats: {
              type: "Mobile",
              regex: "^0?9\\d{9}$",
              example: "09123456789",
              maxLength: 11
            }
          },
          {
            value: "+93",
            label: "\ud83c\udde6\ud83c\uddeb +93",
            description: "Afghanistan",
            phoneFormats: {
              type: "Mobile",
              regex: "^0?7\\d{8}$",
              example: "0701234567",
              maxLength: 10
            }
          },
          {
            value: "+90",
            label: "\ud83c\uddf9\ud83c\uddf7 +90",
            description: "Turkey",
            phoneFormats: {
              type: "Mobile",
              regex: "^0?5\\d{9}$",
              example: "05012345678",
              maxLength: 11
            }
          }
        ]
      },
      {
        path: "select2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "+98"
      },
      {
        path: "selectContry",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.select2.value;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <Input
        data-plasmic-name={"fragmentInput"}
        data-plasmic-override={overrides.fragmentInput}
        className={classNames("__wab_instance", sty.fragmentInput)}
        disabled={
          hasVariant(globalVariants, "screen", "mobileOnly") ? false : undefined
        }
        maxLength={(() => {
          try {
            return $state.fragmentInput.value.startsWith("0")
              ? $state.contry.find(i => i.value == $state.selectContry)
                  .phoneFormats.maxLength
              : $state.contry.find(i => i.value == $state.selectContry)
                  .phoneFormats.maxLength - 1;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
        onChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["fragmentInput", "value"]).apply(
            null,
            eventArgs
          );

          (async value => {
            const $steps = {};

            $steps["runCode"] = true
              ? (() => {
                  const actionArgs = {
                    customFunction: async () => {
                      return ($state.fragmentInput.value =
                        $state.fragmentInput.value.replace(/[^0-9+]/g, ""));
                    }
                  };
                  return (({ customFunction }) => {
                    return customFunction();
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["runCode"] != null &&
              typeof $steps["runCode"] === "object" &&
              typeof $steps["runCode"].then === "function"
            ) {
              $steps["runCode"] = await $steps["runCode"];
            }

            $steps["runCode2"] = true
              ? (() => {
                  const actionArgs = {
                    customFunction: async () => {
                      return (() => {
                        var regix = $state.contry.find(
                          i => i.value == $state.selectContry
                        ).phoneFormats.regex;
                        let reg = new RegExp(regix);
                        if (reg.test($state.fragmentInput.value)) {
                          let inputValue = $state.fragmentInput.value;
                          let countryCode = $state.selectContry;
                          if (countryCode === "+98") {
                            inputValue = inputValue.startsWith("0")
                              ? inputValue
                              : "0" + inputValue;
                            return ($state.number = inputValue);
                          } else {
                            let cleanNumber = inputValue.replace(/^0/, "");
                            return ($state.number = countryCode + cleanNumber);
                          }
                        }
                      })();
                    }
                  };
                  return (({ customFunction }) => {
                    return customFunction();
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["runCode2"] != null &&
              typeof $steps["runCode2"] === "object" &&
              typeof $steps["runCode2"].then === "function"
            ) {
              $steps["runCode2"] = await $steps["runCode2"];
            }
          }).apply(null, eventArgs);
        }}
        placeholder={(() => {
          try {
            return $state.contry.find(item => item.value == $state.selectContry)
              .phoneFormats.example;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
        type={
          hasVariant(globalVariants, "screen", "mobileOnly") ? "tel" : "tel"
        }
        value={generateStateValueProp($state, ["fragmentInput", "value"])}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <AntdSelect
          data-plasmic-name={"select2"}
          data-plasmic-override={overrides.select2}
          bordered={false}
          className={classNames("__wab_instance", sty.select2)}
          defaultStylesClassName={classNames(
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames
          )}
          defaultValue={"+98"}
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["select2", "value"]).apply(
              null,
              eventArgs
            );
          }}
          options={(() => {
            try {
              return $state.contry;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
          placeholder={"Select..."}
          popupScopeClassName={sty["select2__popup"]}
          size={"large"}
          suffixIcon={
            <Icon37Icon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />
          }
          value={generateStateValueProp($state, ["select2", "value"])}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "fragmentInput", "freeBox", "select2", "svg"],
  fragmentInput: ["fragmentInput"],
  freeBox: ["freeBox", "select2", "svg"],
  select2: ["select2", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  fragmentInput: typeof Input;
  freeBox: "div";
  select2: typeof AntdSelect;
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogIn2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogIn2__VariantsArgs;
    args?: PlasmicLogIn2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLogIn2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLogIn2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogIn2__ArgProps,
          internalVariantPropNames: PlasmicLogIn2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogIn2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogIn2";
  } else {
    func.displayName = `PlasmicLogIn2.${nodeName}`;
  }
  return func;
}

export const PlasmicLogIn2 = Object.assign(
  // Top-level PlasmicLogIn2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    fragmentInput: makeNodeComponent("fragmentInput"),
    freeBox: makeNodeComponent("freeBox"),
    select2: makeNodeComponent("select2"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicLogIn2
    internalVariantProps: PlasmicLogIn2__VariantProps,
    internalArgProps: PlasmicLogIn2__ArgProps
  }
);

export default PlasmicLogIn2;
/* prettier-ignore-end */
