/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sZQMbqXz9utLNaTnNb3uss

import {
  createUseStyleTokens,
  createStyleTokensProvider
} from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sZQMbqXz9utLNaTnNb3uss/projectModule

const data = {
  base: `${"plasmic_tokens_sZQMbqXz9utLNaTnNb3uss"} ${"plasmic_tokens_ohDidvG9XsCeFumugENU3J"} ${"plasmic_tokens_jkU633o1Cz7HrJdwdxhVHk"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);

export const StyleTokensProvider = createStyleTokensProvider(
  {
    base: `${"plasmic_tokens_override_sZQMbqXz9utLNaTnNb3uss"} ${data.base}`,
    varianted: data.varianted
  },
  _useGlobalVariants
);
