// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sZQMbqXz9utLNaTnNb3uss
// Component: S_18qgrBezWv

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: sZQMbqXz9utLNaTnNb3uss/projectcss
import sty from "./PlasmicCharge.module.css"; // plasmic-import: S_18qgrBezWv/css

import SimcardAltSvgrepoCom2SvgIcon from "./icons/PlasmicIcon__SimcardAltSvgrepoCom2Svg"; // plasmic-import: i4UpNybEy7gt/icon

createPlasmicElementProxy;

export type PlasmicCharge__VariantMembers = {};
export type PlasmicCharge__VariantsArgs = {};
type VariantPropType = keyof PlasmicCharge__VariantsArgs;
export const PlasmicCharge__VariantProps = new Array<VariantPropType>();

export type PlasmicCharge__ArgsType = {};
type ArgPropType = keyof PlasmicCharge__ArgsType;
export const PlasmicCharge__ArgProps = new Array<ArgPropType>();

export type PlasmicCharge__OverridesType = {
  simcardCharge?: Flex__<"div">;
  simcardIcon?: Flex__<"svg">;
  text?: Flex__<"div">;
};

export interface DefaultChargeProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCharge__RenderFunc(props: {
  variants: PlasmicCharge__VariantsArgs;
  args: PlasmicCharge__ArgsType;
  overrides: PlasmicCharge__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"simcardCharge"}
      data-plasmic-override={overrides.simcardCharge}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.simcardCharge
      )}
      onClick={async event => {
        const $steps = {};

        $steps["goToChargeStep1"] = true
          ? (() => {
              const actionArgs = { destination: `/charging` };
              return (({ destination }) => {
                if (
                  typeof destination === "string" &&
                  destination.startsWith("#")
                ) {
                  document
                    .getElementById(destination.substr(1))
                    .scrollIntoView({ behavior: "smooth" });
                } else {
                  __nextRouter?.push(destination);
                }
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["goToChargeStep1"] != null &&
          typeof $steps["goToChargeStep1"] === "object" &&
          typeof $steps["goToChargeStep1"].then === "function"
        ) {
          $steps["goToChargeStep1"] = await $steps["goToChargeStep1"];
        }
      }}
    >
      <SimcardAltSvgrepoCom2SvgIcon
        data-plasmic-name={"simcardIcon"}
        data-plasmic-override={overrides.simcardIcon}
        className={classNames(projectcss.all, sty.simcardIcon)}
        role={"img"}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"\u062e\u0631\u06cc\u062f \u0634\u0627\u0631\u0698"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  simcardCharge: ["simcardCharge", "simcardIcon", "text"],
  simcardIcon: ["simcardIcon"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  simcardCharge: "div";
  simcardIcon: "svg";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCharge__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCharge__VariantsArgs;
    args?: PlasmicCharge__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCharge__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCharge__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCharge__ArgProps,
          internalVariantPropNames: PlasmicCharge__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCharge__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "simcardCharge") {
    func.displayName = "PlasmicCharge";
  } else {
    func.displayName = `PlasmicCharge.${nodeName}`;
  }
  return func;
}

export const PlasmicCharge = Object.assign(
  // Top-level PlasmicCharge renders the root element
  makeNodeComponent("simcardCharge"),
  {
    // Helper components rendering sub-elements
    simcardIcon: makeNodeComponent("simcardIcon"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicCharge
    internalVariantProps: PlasmicCharge__VariantProps,
    internalArgProps: PlasmicCharge__ArgProps
  }
);

export default PlasmicCharge;
/* prettier-ignore-end */
