/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sZQMbqXz9utLNaTnNb3uss
// Component: VmoOciQ82xNG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Button from "../../Button"; // plasmic-import: _5H7Xe2DiXqI/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sZQMbqXz9utLNaTnNb3uss/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sZQMbqXz9utLNaTnNb3uss/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicResult.module.css"; // plasmic-import: VmoOciQ82xNG/css

import TickCircleIcon from "./icons/PlasmicIcon__TickCircle"; // plasmic-import: PaDfWDk2nA1C/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: GsFYrYWA9bY1/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: DuoBqJ29N7bW/icon
import Icon172Icon from "./icons/PlasmicIcon__Icon172"; // plasmic-import: VlGyiY8DbZtu/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: jg6gpiNRWEQd/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicResult__VariantMembers = {
  success: "_true" | "_false";
};
export type PlasmicResult__VariantsArgs = {
  success?: SingleChoiceArg<"_true" | "_false">;
};
type VariantPropType = keyof PlasmicResult__VariantsArgs;
export const PlasmicResult__VariantProps = new Array<VariantPropType>(
  "success"
);

export type PlasmicResult__ArgsType = {};
type ArgPropType = keyof PlasmicResult__ArgsType;
export const PlasmicResult__ArgProps = new Array<ArgPropType>();

export type PlasmicResult__OverridesType = {
  root?: Flex__<"div">;
  button?: Flex__<typeof Button>;
  button2?: Flex__<typeof Button>;
};

export interface DefaultResultProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicResult__RenderFunc(props: {
  variants: PlasmicResult__VariantsArgs;
  args: PlasmicResult__ArgsType;
  overrides: PlasmicResult__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "button.loadingviow",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.loadingviow;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "button2.loadingviow",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.loadingviow;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "success",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return `_${$ctx.query.success}`;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.success
      }
    ],
    [$props, $ctx, $refs]
  );

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_sZQMbqXz9utLNaTnNb3uss",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root,
            {
              [sty.rootsuccess__false]: hasVariant($state, "success", "_false"),
              [sty.rootsuccess__true]: hasVariant($state, "success", "_true")
            }
          )}
        >
          <div
            className={classNames("all", sty.freeBox__tga10, {
              [sty.freeBoxsuccess__false__tga10Dibh2]: hasVariant(
                $state,
                "success",
                "_false"
              ),
              [sty.freeBoxsuccess__true__tga10XxTpl]: hasVariant(
                $state,
                "success",
                "_true"
              )
            })}
          >
            <div className={classNames("all", sty.freeBox___6Myk)}>
              <TickCircleIcon
                className={classNames("all", sty.svg__evTeD)}
                role={"img"}
              />
            </div>
            <div className={classNames("all", "__wab_text", sty.text__hHeKh)}>
              {
                "\u067e\u0631\u062f\u0627\u062e\u062a \u0628\u0627 \u0645\u0648\u0641\u0642\u06cc\u062a \u0627\u0646\u062c\u0627\u0645 \u0634\u062f"
              }
            </div>
            <div className={classNames("all", "__wab_text", sty.text__d2CwC)}>
              {
                "\u062a\u0631\u0627\u06a9\u0646\u0634 \u0634\u0645\u0627 \u0628\u0627 \u0645\u0648\u0641\u0642\u06cc\u062a \u062a\u0627\u06cc\u06cc\u062f \u0648 \u062b\u0628\u062a \u0634\u062f."
              }
            </div>
            <div className={classNames("all", sty.freeBox__vNy3O)}>
              <div className={classNames("all", sty.freeBox__zYmOo)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__pCnx7)}
                >
                  {
                    "\u0634\u0645\u0627\u0631\u0647 \u067e\u06cc\u06af\u06cc\u0631\u06cc:"
                  }
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__dj84U)}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $ctx.query.ref_no;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "5000989898";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__veiA0)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__go7Is)}
                >
                  {
                    "\u0634\u0645\u0627\u0631\u0647 \u0633\u0641\u0627\u0631\u0634:"
                  }
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__xnTH, {
                    [sty.textsuccess__false__xnTHdibh2]: hasVariant(
                      $state,
                      "success",
                      "_false"
                    )
                  })}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $ctx.query.order_id;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "6565656556565";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </div>
            </div>
            <Button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames("__wab_instance", sty.button, {
                [sty.buttonsuccess__false]: hasVariant(
                  $state,
                  "success",
                  "_false"
                ),
                [sty.buttonsuccess__true]: hasVariant(
                  $state,
                  "success",
                  "_true"
                )
              })}
              color={"green"}
              link={
                hasVariant($state, "success", "_false") &&
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "baBarkat://"
                  : hasVariant($state, "success", "_false")
                    ? "baBarkat://"
                    : "baBarkat://"
              }
              loadingviow={generateStateValueProp($state, [
                "button",
                "loadingviow"
              ])}
              onClick={async event => {
                const $steps = {};

                $steps["updateButtonLoadingviow"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["button", "loadingviow"]
                        },
                        operation: 0
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateButtonLoadingviow"] != null &&
                  typeof $steps["updateButtonLoadingviow"] === "object" &&
                  typeof $steps["updateButtonLoadingviow"].then === "function"
                ) {
                  $steps["updateButtonLoadingviow"] =
                    await $steps["updateButtonLoadingviow"];
                }
              }}
              onLoadingviowChange={async (...eventArgs: any) => {
                ((...eventArgs) => {
                  generateStateOnChangeProp($state, ["button", "loadingviow"])(
                    eventArgs[0]
                  );
                }).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              {
                "\u0628\u0627\u0632\u06af\u0634\u062a \u0628\u0647 \u0627\u067e\u0644\u06cc\u06a9\u06cc\u0634\u0646"
              }
            </Button>
          </div>
          <div
            className={classNames("all", sty.freeBox__xohn6, {
              [sty.freeBoxsuccess__false__xohn6Dibh2]: hasVariant(
                $state,
                "success",
                "_false"
              ),
              [sty.freeBoxsuccess__true__xohn6XxTpl]: hasVariant(
                $state,
                "success",
                "_true"
              )
            })}
          >
            <div className={classNames("all", sty.freeBox__vbOpd)}>
              <PlasmicIcon__
                PlasmicIconType={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? Icon172Icon
                    : Icon172Icon
                }
                className={classNames("all", sty.svg__f3KjB)}
                role={"img"}
              />
            </div>
            <div className={classNames("all", "__wab_text", sty.text__suElF)}>
              {hasVariant(globalVariants, "screen", "mobileOnly")
                ? "\u067e\u0631\u062f\u0627\u062e\u062a \u0646\u0627\u0645\u0648\u0641\u0642 \u0628\u0648\u062f"
                : "\u067e\u0631\u062f\u0627\u062e\u062a \u0646\u0627\u0645\u0648\u0641\u0642 \u0628\u0648\u062f"}
            </div>
            <div className={classNames("all", "__wab_text", sty.text__ur5C)}>
              {
                "\u062a\u0631\u0627\u06a9\u0646\u0634 \u0634\u0645\u0627 \u0628\u0627 \u0645\u0634\u06a9\u0644 \u0645\u0648\u062c\u0647 \u0634\u062f."
              }
            </div>
            <div
              className={classNames("all", sty.freeBox__ke0Q2, {
                [sty.freeBoxsuccess__false__ke0Q2Dibh2]: hasVariant(
                  $state,
                  "success",
                  "_false"
                )
              })}
            >
              <div
                className={classNames("all", sty.freeBox__deBeL, {
                  [sty.freeBoxsuccess__false__deBeLdibh2]: hasVariant(
                    $state,
                    "success",
                    "_false"
                  )
                })}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__yWNe5, {
                    [sty.textsuccess__false__yWNe5Dibh2]: hasVariant(
                      $state,
                      "success",
                      "_false"
                    )
                  })}
                >
                  {
                    "\u0634\u0645\u0627\u0631\u0647 \u067e\u06cc\u06af\u06cc\u0631\u06cc:"
                  }
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text___3MriT)}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $ctx.query.ref_no;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "5000989898";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__geTqp)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__jiYky)}
                >
                  {
                    "\u0634\u0645\u0627\u0631\u0647 \u0633\u0641\u0627\u0631\u0634:"
                  }
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__dsuIa)}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $ctx.query.order_id;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "6565656556565";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </div>
            </div>
            <Button
              data-plasmic-name={"button2"}
              data-plasmic-override={overrides.button2}
              className={classNames("__wab_instance", sty.button2, {
                [sty.button2success__false]: hasVariant(
                  $state,
                  "success",
                  "_false"
                ),
                [sty.button2success__true]: hasVariant(
                  $state,
                  "success",
                  "_true"
                )
              })}
              color={"black"}
              link={"baBarkat://"}
              loadingviow={generateStateValueProp($state, [
                "button2",
                "loadingviow"
              ])}
              onLoadingviowChange={async (...eventArgs: any) => {
                ((...eventArgs) => {
                  generateStateOnChangeProp($state, ["button2", "loadingviow"])(
                    eventArgs[0]
                  );
                }).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
            >
              {
                "\u0628\u0627\u0632\u06af\u0634\u062a \u0628\u0647 \u0627\u067e\u0644\u06cc\u06a9\u06cc\u0634\u0646"
              }
            </Button>
          </div>
          <IconIcon
            className={classNames("all", sty.svg__p57MA, {
              [sty.svgsuccess__false__p57MAdibh2]: hasVariant(
                $state,
                "success",
                "_false"
              ),
              [sty.svgsuccess__true__p57MAXxTpl]: hasVariant(
                $state,
                "success",
                "_true"
              )
            })}
            role={"img"}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "button", "button2"],
  button: ["button"],
  button2: ["button2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  button: typeof Button;
  button2: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicResult__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicResult__VariantsArgs;
    args?: PlasmicResult__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicResult__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicResult__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicResult__ArgProps,
          internalVariantPropNames: PlasmicResult__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicResult__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicResult";
  } else {
    func.displayName = `PlasmicResult.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "sZQMbqXz9utLNaTnNb3uss"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicResult = Object.assign(
  // Top-level PlasmicResult renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),
    button2: makeNodeComponent("button2"),

    // Metadata about props expected for PlasmicResult
    internalVariantProps: PlasmicResult__VariantProps,
    internalArgProps: PlasmicResult__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/payResult",
      pagePath: "/payResult",
      params: {},
      query: {}
    })
  }
);

export default PlasmicResult;
/* prettier-ignore-end */
