// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicSlideinModal2,
  DefaultSlideinModal2Props
} from "./plasmic/babarkat/PlasmicSlideinModal2";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface SlideinModal2Props extends Omit<DefaultSlideinModal2Props, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultSlideinModal2Props altogether and have
// total control over the props for your component.
export interface SlideinModal2Props extends DefaultSlideinModal2Props {}

function SlideinModal2_(
  props: SlideinModal2Props,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicSlideinModal2 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicSlideinModal2 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all SlideinModal2Props here, but feel free
  // to do whatever works for you.

  return <PlasmicSlideinModal2 root={{ ref }} {...props} />;
}

const SlideinModal2 = React.forwardRef(SlideinModal2_);
export default SlideinModal2;
