// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../../components/plasmic/babarkat/PlasmicGlobalContextsProvider";
import { StyleTokensProvider } from "../../components/plasmic/babarkat/PlasmicStyleTokensProvider";
import { UnnamedGlobalGroupOfVariantsContextProvider } from "../../components/plasmic/babarkat/PlasmicGlobalVariant__UnnamedGlobalGroupOfVariants";
import { UnnamedGlobalGroupOfVariants2ContextProvider } from "../../components/plasmic/babarkat/PlasmicGlobalVariant__UnnamedGlobalGroupOfVariants2";
import { PlasmicResult } from "../../components/plasmic/babarkat/PlasmicResult";
import { useRouter } from "next/router";
import { PlasmicQueryDataProvider } from "@plasmicapp/react-web/lib/query";

function Result() {
  // Use PlasmicResult to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicResult are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicResult is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).

  return (
    <UnnamedGlobalGroupOfVariants2ContextProvider value={undefined}>
      <UnnamedGlobalGroupOfVariantsContextProvider value={undefined}>
        <GlobalContextsProvider>
          <PlasmicQueryDataProvider>
            <PageParamsProvider__
              route={useRouter()?.pathname}
              params={useRouter()?.query}
              query={useRouter()?.query}
            >
              <StyleTokensProvider>
                <PlasmicResult />
              </StyleTokensProvider>
            </PageParamsProvider__>
          </PlasmicQueryDataProvider>
        </GlobalContextsProvider>
      </UnnamedGlobalGroupOfVariantsContextProvider>
    </UnnamedGlobalGroupOfVariants2ContextProvider>
  );
}

export default Result;
