/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: a3pmZtcpA5asHkNtN3SGoF

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: a3pmZtcpA5asHkNtN3SGoF/projectModule

const data = {
  base: `${"plasmic_tokens_a3pmZtcpA5asHkNtN3SGoF"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
